title: The Lifted Initiative
description: >-
  Promoting the widespread adoption of environmentally-positive, open source
  decentralized technology.
baseurl: ""
url: "https://liftedinit.org"

collections:
  - projects

twitter_username: liftedinit
github_username: liftedinit
linkedin_username: liftedinit

plugins:
  #  - jekyll-feed
